/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academics;

import static academics.LibraryManagement.TotalFine;
import static academics.LibraryManagement.passdatabase;
import static academics.LibraryManagement.urldatabase;
import static academics.LibraryManagement.useroot;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Payment extends javax.swing.JDialog {

    static int fineremaining;
    static int payment;
    /**
     * Creates new form Payment
     */
    public Payment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        pay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setBackground(new java.awt.Color(240, 248, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setText("Total Fine");

        jLabel2.setBackground(new java.awt.Color(240, 248, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("Payment");
        jLabel2.setBorder(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jTextField1.setBorder(null);

        jTextField2.setFont(new java.awt.Font("Lucida Sans", 0, 18));
        jTextField2.setBorder(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        pay.setBackground(new java.awt.Color(25, 25, 112));
        pay.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        pay.setForeground(new java.awt.Color(255, 255, 255));
        pay.setText("Pay");
        pay.setBorder(null);
        pay.setBorderPainted(false);
        pay.setContentAreaFilled(false);
        pay.setFocusable(false);
        pay.setOpaque(true);
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(444, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
       String paid=jTextField2.getText();
        
       String book_id=LibraryManagement.jTextField16.getText();
       String std_id="";
       
     
      if(paid.equals(""))
       {
           JOptionPane.showMessageDialog(this,"Please enter the amount","Alert",JOptionPane.WARNING_MESSAGE);
           return;
       }
       else if( (payment > LibraryManagement.TotalFine) || (payment < 0 ))
       {
            JOptionPane.showMessageDialog(this, "Please enter the correct amount", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
       }
       else
       {   
           payment=Integer.parseInt(paid);
         
           try {
            Connection con = null;
            con = DriverManager.getConnection(urldatabase, useroot, passdatabase);
           
            String query = "select std_id from bookissued where book_id='" + book_id + "'";

            Statement st = con.createStatement();
            ResultSet sr = st.executeQuery(query);
            while (sr.next()) {
                std_id = sr.getString(1);
            }
            int remainingfine = TotalFine - payment;
            if (remainingfine != 0) {

                System.out.println(std_id);
                String query2 = "select * from finebook where stu_id='" + std_id + "'";
                Statement sa = con.createStatement();
                ResultSet ss = sa.executeQuery(query2);
                if (ss.next()) {
                    String updatequery = "update finebook set FinePending= ? where stu_id=?";
                    PreparedStatement sl = con.prepareStatement(updatequery);
                    sl.setString(1, String.valueOf(remainingfine));
                    sl.setString(2, std_id);
                    sl.executeUpdate();
                    sl.close();

                } else {
                    String insertquery = "insert into finebook values(?,?)";
                    PreparedStatement sv = con.prepareStatement(insertquery);
                    sv.setString(1, std_id);
                    sv.setString(2, String.valueOf(remainingfine));
                    sv.executeUpdate();
                    sv.close();
                }
                ss.close();
                sa.close();
            }
              String query3 = "update bookissued set doi=?,dos=? where book_id=?";
            PreparedStatement one = con.prepareStatement(query3);
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date d = new Date();
            String reissuedate = dateFormat.format(d);
            LocalDate after = LocalDate.now().plusDays(15);
            String reissuedsubmission = after.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            one.setString(1, reissuedate);
            one.setString(2, reissuedsubmission);
            one.setString(3, book_id);
            one.executeUpdate();
            TotalFine=0;
            LibraryManagement.jTextField16.setText("");
            LibraryManagement.jTextField17.setText("");
            LibraryManagement.jTextField18.setText("");
            LibraryManagement.jTextField19.setText("");
            LibraryManagement.jTextField20.setText("");
            LibraryManagement.jTextField21.setText("");
            LibraryManagement.jTextField22.setText("");
            LibraryManagement.jTextField23.setText("");
            LibraryManagement.jTextField24.setText("");
            LibraryManagement.jTextField25.setText("");
            if (remainingfine == 0) {
                System.out.println("reached here");
                String query4 = "delete from finebook where stu_id=?";
                PreparedStatement sm = con.prepareStatement(query4);
                sm.setString(1, std_id);
                sm.execute();

            }
       }   catch (SQLException ex) {
               Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
           }
             dispose();
       }
      
    }//GEN-LAST:event_payActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
          if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')|| evt.getKeyChar()=='\b') {
               jTextField2.setEditable(true);
               
            } else {
               jTextField2.setEditable(false);
               
            }
    }//GEN-LAST:event_jTextField2KeyPressed
    public static void pay()
    {
      jTextField1.setText(String.valueOf(LibraryManagement.TotalFine));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
            Login.loadingsqldriver();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payment dialog = new Payment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    public static javax.swing.JButton pay;
    // End of variables declaration//GEN-END:variables
}
